### ISSUE TITLE
Static links to pages don't redirect properly

### ISSUE THREAD

**Issue by taylorreece** [PagerDuty/developer-docs#19]
I had a link from my docs to your docs at https://developer.pagerduty.com/docs/events-api-v2/overview/ that worked previously. Now when I click the link I get redirected to a page that shows an error:

![image](https://user-images.githubusercontent.com/3622586/151255708-3e5e0d61-f29a-45aa-bec5-75f7b84ab5d9.png)

If I refresh my page with the URL I'm redirect to, it works:

![image](https://user-images.githubusercontent.com/3622586/151255782-e9f5edd2-13d5-467e-bfab-57cf9364463e.png)

What's up with those build hashes at the beginning of URLs (the `ZG9jOjExMDI5NTgw`)? Are those stable (like, can I link to https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgw-events-api-v2-overview and expect that URL to exist after the next time a deploy happens)? Should I be linking to the URLs with prepended hashes instead of the "nice" looking URLs?

Thanks!

**Comment by Jimbo1167** [comment]
Hey @taylorreece thanks for the report, this _should_ hopefully be fixed now! Please let us know if you find any other redirects not working.

As a quick follow up - the hashes at the beginning are indeed stable, but if you prefer the previous URL, we will now redirect to the new hash properly.

**Comment by taylorreece** [comment]
Worked like a charm - thanks @Jimbo1167 !
